# Set service name - allowed characters: a-z, A-Z, 0-9, -, _ and space
# # Defaults to the name of your Rails app
service_name: 'PoC'
#
# # Use if APM Server requires a token
# # secret_token: ''
#
# # Set custom APM Server URL (default: http://localhost:8200)
server_url: 'http://ec2-3-214-219-124.compute-1.amazonaws.com:8200'
